name: Lint, build and deploy

on: push

jobs:
  lint:
    name: Lint code base
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

# Replaced by Checkstyle for Java action. May use it if #1167 is solved and the bot uses more
# than one language that should be linted
#    - name: Run Super-Linter
#      uses: github/super-linter@v3
#      env:
#        DEFAULT_BRANCH: master
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#
#        VALIDATE_ALL_CODEBASE: false
#        VALIDATE_YAML: false
#        VALIDATE_XML: false
#        VALIDATE_GROOVY: false
#        Ignore gradle wrapper files
#        FILTER_REGEX_EXCLUDE: gradlew|gradlew\.bat|gradle\/.*
    - name: Run Checkstyle
      uses: dbelyaev/action-checkstyle@master
      with:
        checkstyle_config: .github/linters/sun_checks.xml
        reporter: github-check
        filter_mode: file
        fail_on_error: true
        workdir: src/main

  build:
    name: Build
    runs-on: ubuntu-20.04
    needs: lint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Make gradle wrapper executable
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew build

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: success()
        with:
          path: build/libs/*.jar

  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-20.04
    needs: build
    if: ${{ github.ref == 'refs/heads/master' && ! startsWith(github.event.head_commit.message, '[nodeploy]') }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
