name: Lint, build and deploy

on:
  push:
    branches:
      - master

jobs:
  lint:
    name: Lint code base
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Super-Linter
      uses: github/super-linter@v3
      env:
        DEFAULT_BRANCH: master
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        VALIDATE_ALL_CODEBASE: false
        VALIDATE_YAML: false
        VALIDATE_XML: false
        VALIDATE_GROOVY: false

  build:
    name: Build
    runs-on: ubuntu-20.04
    needs: lint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Make gradle wrapper executable
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew build

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: success()
        with:
          path: build/libs/*.jar

#  deploy:
#    name: Deploy to Heroku
#    runs-on: ubuntu-20.04
#    needs: build
#
#    steps:
#    - name: Checkout repository
#      uses: actions/checkout@v2
#    - name: Deploy to Heroku
#      uses: akhileshns/heroku-deploy@v3.8.9
#      with:
#        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
#        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
#        heroku_email: ${{ secrets.HEROKU_EMAIL }}
