package cobaltumsmp.discordbot.module.ticketsystem;

import cobaltumsmp.discordbot.module.ticketsystem.auto._Datamap;

/**
 * Generated by Cayenne. I don't know what this does.
 */
public class Datamap extends _Datamap {

    private static Datamap instance;

    private Datamap() {}

    /**
     * Get the current {@link Datamap} instance.
     */
    public static Datamap getInstance() {
        if (instance == null) {
            instance = new Datamap();
        }

        return instance;
    }
}
